
package soap.soap;

import soap.CarDetectorService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CardDetectorService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/webservices/soap?wsdl")
public class CardDetectorService
        extends Service {

    private final static URL CARDDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARDDETECTORSERVICE_EXCEPTION;
    private final static QName CARDDETECTORSERVICE_QNAME = new QName("http://soap/", "CardDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservices/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDDETECTORSERVICE_WSDL_LOCATION = url;
        CARDDETECTORSERVICE_EXCEPTION = e;
    }

    public CardDetectorService() {
        super(__getWsdlLocation(), CARDDETECTORSERVICE_QNAME);
    }

    public CardDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDDETECTORSERVICE_QNAME, features);
    }

    public CardDetectorService(URL wsdlLocation) {
        super(wsdlLocation, CARDDETECTORSERVICE_QNAME);
    }

    public CardDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDDETECTORSERVICE_QNAME, features);
    }

    public CardDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CarDetectorService
     */
    @WebEndpoint(name = "CarDetector")
    public soap.CarDetectorService getCarDetector() {
        return super.getPort(new QName("http://soap/", "CarDetector"), CarDetectorService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CarDetectorService
     */
    @WebEndpoint(name = "CarDetector")
    public soap.CarDetectorService getCarDetector(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "CarDetector"), CarDetectorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDDETECTORSERVICE_EXCEPTION != null) {
            throw CARDDETECTORSERVICE_EXCEPTION;
        }
        return CARDDETECTORSERVICE_WSDL_LOCATION;
    }

}
